# Pact broker and postgres all combined in a single docker-compose formula.
# Based on: https://github.com/DiUS/pact_broker-docker/blob/master/docker-compose.yml
# See the accompanying README file on https://github.com/DiUS/pact_broker-docker
# To start up the pact broker, just run "docker-compose up" in the same folder.

version: '3'

services:

  postgres:
    image: postgres
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: AdminOfPactBrokerDb
      POSTGRES_DB: postgres

  broker_app:
    image: dius/pact-broker
    ports:
    - "80:80"
    links:
    - postgres
    environment:
      PACT_BROKER_DATABASE_ADAPTER: postgres
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: AdminOfPactBrokerDb
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: postgres

  nginx:
    image: nginx:alpine
    links:
    - broker_app:broker
    volumes:
    - ./ssl/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./ssl:/etc/nginx/ssl
    ports:
    - "8443:443"